### ISSUE TITLE
gopkgs.com early EOF

### ISSUE THREAD

**Issue by jhvst** [rainycape/unidecode#1]
Hi,

I'm having difficulties cloning or `go get`ting this package.

If I run `go get gopkgs.com/unidecode.v1` I get error saying:

```
~/Github $ go get gopkgs.com/unidecode.v1
# cd .; git clone http://gopkgs.com/unidecode.v1 /Users/juuso/.gvm/pkgsets/go1.3.3/global/src/gopkgs.com/unidecode.v1
Cloning into '/Users/juuso/.gvm/pkgsets/go1.3.3/global/src/gopkgs.com/unidecode.v1'...
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: unpack-objects failed
package gopkgs.com/unidecode.v1: exit status 128
```

Running `git clone http://gopkgs.com/unidecode.v1` prints:

```
~/Github $ git clone http://gopkgs.com/unidecode.v1
Cloning into 'unidecode.v1'...
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: unpack-objects failed
```

However, forking your project and cloning it works fine. Therefore I'd expect there would be something wrong with `gopkgs.com`.

I'd appreciate if you could take a look at this matter, as some projects which have the [old repository](https://github.com/fiam/gounidecode) as dependency are failing `go build`'s on Linux.

Once this package is working, I could notify the other repository owners about the issue. Otherwise I'm afraid I need to do some major vendoring on my application.

Here are my current software versions as well:
`git version 2.0.1`
`go version go1.3.3 darwin/amd64`

Although, as I use version manager I can say that changing the go version to 1.2 does not help either.

**Comment by avelino** [comment]
I used Go 1.4..2
```
avelino@kml ~ $ go get gopkgs.com/unidecode.v1
# cd .; git clone http://gopkgs.com/unidecode.v1 /home/avelino/ownCloud/avelino/projects/go/src/gopkgs.com/unidecode.v1
Cloning into '/home/avelino/ownCloud/avelino/projects/go/src/gopkgs.com/unidecode.v1'...
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: unpack-objects failed
package gopkgs.com/unidecode.v1: exit status 128
```
```
avelino@kml ~ $ go version  
go version go1.4.2 linux/amd64
```
