### ISSUE TITLE
Copyright owner

### ISSUE THREAD

**Issue by aviau** [rainycape/unidecode#4]
Hello!

I am packaging unidecode for Debian and I woulld like clarifications on who is the copyright owner.

Rainycape was the one to commit the license (https://github.com/rainycape/unidecode/commit/4d525912b5d0c9da8c2c76b30bb0e4c8b7b4d01b). so I assume that the owner is the following:
```
2014 Rainy Cape S.L. <hello@rainycape.com>
```

Is that correct?

**Comment by rainycape** [comment]
@aviau I'm glad to know you're packaging it for Debian! That's correct, Rainy Cape S.L. is the copyright owner. Note that in the practice it wouldn't make much difference, since I (Alberto GH, @fiam on GitHub) I'm also the owner of Rainy Cape S.L..

**Comment by onlyjob** [comment]
Thanks for confirming that. Please note that copyright attribution should be included to `LICENSE` file or to source files' headers (or both). Please commit this information or we may not be able to pass gatekeeper's review necessary for acceptance to Debian. Thank you.
